name: Nightly Build
on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'pyg-team/pytorch_geometric'
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Set version
        run: echo "VERSION=$(sed -n "s/^__version__ = '\(.*\)'/\1/p" torch_geometric/__init__.py)"
          >> ${GITHUB_ENV}
      - id: measurement-4
        name: Record Measurement After Set version
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Set version
          task: get-measurement
      - name: Set time
        run: echo "TODAY=$(date +'%Y%m%d')" >> ${GITHUB_ENV}
      - id: measurement-6
        name: Record Measurement After Set time
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Set time
          task: get-measurement
      - name: Customize build version
        run: 'sed -i "s/$VERSION/$VERSION.dev$TODAY/" torch_geometric/__init__.py

          sed -i ''0,/name="torch-geometric"/s//name="pyg-nightly"/'' pyproject.toml
          # Only change first occurence

          sed -i "s/version=\"$VERSION\"/version=\"$VERSION.dev$TODAY\"/" pyproject.toml

          '
      - id: measurement-8
        name: Record Measurement After Customize build version
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Customize build version
          task: get-measurement
      - name: Build package
        run: 'pip install build

          python -m build

          '
      - id: measurement-10
        name: Record Measurement After Build package
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Build package
          task: get-measurement
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          user: __token__
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
