name: Linting
on:
  push:
    branches:
      - master

concurrency:
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ startsWith(github.ref, 'refs/pull/') || github.run_number }}
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 40
      - id: changed-files-specific
        name: Get changed files
        uses: tj-actions/changed-files@v46
        with:
          files: 'benchmark/**

            conda/**

            docker/**

            docs/**

            examples/**

            graphgym/**

            README.md

            CHANGELOG.md

            '
      - if: steps.changed-files-specific.outputs.only_changed != 'true'
        name: Setup packages
        uses: ./.github/actions/setup
      - if: steps.changed-files-specific.outputs.only_changed != 'true'
        name: Install main package
        run: 'uv pip install mypy

          uv pip install -e ".[full,test]"

          uv pip install types-requests

          '
      - id: measurement-5
        name: Record Measurement After Install main package
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install main package
          task: get-measurement
      - if: steps.changed-files-specific.outputs.only_changed != 'true'
        name: Check type hints
        run: 'uv run --no-project mypy --cache-dir=/dev/null

          '
      - id: measurement-7
        name: Record Measurement After Check type hints
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Check type hints
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
