name: Testing RAG
on:
  push:
    branches:
      - master

concurrency:
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ startsWith(github.ref, 'refs/pull/') || github.run_number }}
jobs:
  rag_pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 40
      - id: changed-files-specific-rag
        name: Get changed files
        uses: tj-actions/changed-files@v46
        with:
          files: 'torch_geometric/datasets/web_qsp_dataset.py

            torch_geometric/nn/nlp/**

            torch_geometric/nn/models/g_retriever.py

            torch_geometric/loader/rag_loader.py

            '
      - if: steps.changed-files-specific-rag.outputs.any_changed == 'true'
        name: Setup packages
        uses: ./.github/actions/setup
        with:
          full_install: false
      - if: steps.changed-files-specific-rag.outputs.any_changed == 'true'
        name: Install main package
        run: 'uv pip install -e ".[test,rag]"

          '
      - id: measurement-5
        name: Record Measurement After Install main package
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install main package
          task: get-measurement
      - if: steps.changed-files-specific-rag.outputs.any_changed == 'true'
        name: Run tests
        run: 'RAG_TEST=1 uv run --no-project pytest -m rag --durations 10

          '
        timeout-minutes: 10
      - id: measurement-7
        name: Record Measurement After Run tests
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Run tests
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
